package com.example.legacy;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Calendar;
import java.util.List;
import java.util.TimeZone;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * {@link LegacySalesReport} 的行为契约 —— 迁移前后必须逐条为真。
 *
 * <h2>这组测试是「迁移评测」的一部分，不是普通单测</h2>
 * <p>RemasterAgent 的 VERIFY 节点会在沙箱里执行 {@code mvn test}，把通过率作为模型改写质量的
 * 唯一客观依据。所以这些断言的作用是<b>把可观测行为钉死</b>，让「模型改动了语义」这件事
 * 一定表现为一条失败用例，而不是一句「看起来改得挺好」。
 *
 * <p>因此这里有两条自律：
 * <ol>
 *   <li><b>不依赖不确定性输入。</b>凡涉及时间的地方一律注入固定的 epoch 毫秒
 *       （{@link #FIXED_EPOCH_MILLIS} = 2023-11-14T22:13:20Z），断言可以直接写死字符串。</li>
 *   <li><b>只断言可观测结果，不断言实现细节。</b>例如「{@code ranked()} 返回的是快照」
 *       用「取完之后再追加金额，已取出的列表不变」来表达，而不是去改返回列表 ——
 *       后者会把「返回可变 ArrayList」这种实现细节固化成契约，
 *       一旦模型改用 {@code Stream.toList()}（不可变）就会被误判为回归。</li>
 * </ol>
 */
class LegacySalesReportTest {

    /** 2023-11-14T22:13:20Z。写死它，让所有日期断言变成纯字符串比较。 */
    private static final long FIXED_EPOCH_MILLIS = 1_700_000_000_000L;

    /** 期望的时间戳文本，与 {@link #FIXED_EPOCH_MILLIS} 一一对应。 */
    private static final String EXPECTED_TIMESTAMP = "2023-11-14 22:13:20";

    private static final String EXPECTED_FOOTER = "----\n"
            + "legacy-demo sales report\n"
            + "generated by RemasterAgent migration sample\n";

    private static LegacySalesReport reportWith(double... amounts) {
        LegacySalesReport report = new LegacySalesReport(FIXED_EPOCH_MILLIS);
        for (double amount : amounts) {
            report.addAmount(amount);
        }
        return report;
    }

    // ------------------------------------------------------------------
    // 聚合
    // ------------------------------------------------------------------

    @Test
    @DisplayName("空报表：数量 0、合计 0、均值 0，且不抛异常")
    void emptyReport() {
        LegacySalesReport report = reportWith();

        assertEquals(0, report.size());
        assertEquals(0d, report.total(), 1e-9);
        assertEquals(0d, report.average(), 1e-9, "空报表的均值定义为 0，不是异常");
    }

    @Test
    @DisplayName("合计与均值按 double 语义累加")
    void totalAndAverage() {
        LegacySalesReport report = reportWith(10d, 30d, 20d);

        assertEquals(3, report.size());
        assertEquals(60d, report.total(), 1e-9);
        assertEquals(20d, report.average(), 1e-9);
    }

    @Test
    @DisplayName("允许 0 与负数金额（退货场景）计入合计")
    void zeroAndNegativeAmountsAreAccepted() {
        LegacySalesReport report = reportWith(100d, -40d, 0d);

        assertEquals(3, report.size());
        assertEquals(60d, report.total(), 1e-9);
    }

    // ------------------------------------------------------------------
    // 排序
    // ------------------------------------------------------------------

    @Test
    @DisplayName("榜单按金额从高到低")
    void rankedIsDescending() {
        assertEquals(List.of(30d, 20d, 10d), reportWith(10d, 30d, 20d).ranked());
    }

    @Test
    @DisplayName("金额相同时不丢数据、不互相覆盖")
    void rankedKeepsDuplicates() {
        assertEquals(List.of(25d, 25d, 5d), reportWith(25d, 5d, 25d).ranked());
    }

    @Test
    @DisplayName("榜单是快照：取完之后再追加金额，已取出的榜单不变")
    void rankedIsSnapshot() {
        LegacySalesReport report = reportWith(10d, 20d);

        List<Double> snapshot = report.ranked();
        report.addAmount(99d);

        assertEquals(List.of(20d, 10d), snapshot);
        assertEquals(List.of(99d, 20d, 10d), report.ranked(), "新取出的榜单应当包含新金额");
    }

    // ------------------------------------------------------------------
    // 时间
    // ------------------------------------------------------------------

    @Test
    @DisplayName("UTC 日期文本")
    void generatedDateInUtc() {
        assertEquals("2023-11-14", reportWith(1d).generatedDateUtc());
        assertEquals("1970-01-01", new LegacySalesReport(0L).generatedDateUtc());
    }

    @Test
    @DisplayName("按自然月判断生成时刻，月份从 1 开始")
    void generatedInMonth() {
        LegacySalesReport report = reportWith(1d);

        assertTrue(report.generatedInMonth(2023, 11));
        assertFalse(report.generatedInMonth(2023, 12));
        assertFalse(report.generatedInMonth(2024, 11));
    }

    @Test
    @DisplayName("头部带 UTC 时间戳")
    void headerContainsUtcTimestamp() {
        assertEquals("Sales report generated at " + EXPECTED_TIMESTAMP + " (UTC)",
                reportWith(1d).header());
    }

    @Test
    @DisplayName("脚注是三行固定文本")
    void footerIsFixedText() {
        assertEquals(EXPECTED_FOOTER, reportWith(1d).footer());
    }

    // ------------------------------------------------------------------
    // 渲染
    // ------------------------------------------------------------------

    @Test
    @DisplayName("榜单每行形如「序号: 美元金额」")
    void topLinesFormatting() {
        LegacySalesReport report = reportWith(10d, 30d, 20d);

        assertEquals("1: $30.00\n2: $20.00", report.topLines(2));
        assertEquals("1: $30.00", report.topLines(1));
    }

    @Test
    @DisplayName("n 超过实际条数时按实际条数输出，不补空行")
    void topLinesClampsToSize() {
        assertEquals("1: $30.00\n2: $20.00\n3: $10.00", reportWith(10d, 30d, 20d).topLines(99));
        assertEquals("", reportWith().topLines(5));
    }

    @Test
    @DisplayName("空报表的完整渲染 = 头部 + 脚注，没有空的榜单段")
    void renderEmptyReport() {
        LegacySalesReport report = reportWith();

        assertEquals(report.header() + "\n" + EXPECTED_FOOTER, report.render(3));
    }

    @Test
    @DisplayName("完整渲染 = 头部 + 榜单 + 脚注")
    void renderFullReport() {
        LegacySalesReport report = reportWith(10d, 30d);

        assertEquals(report.header() + "\n1: $30.00\n2: $10.00\n" + EXPECTED_FOOTER, report.render(2));
    }

    @Test
    @DisplayName("无参构造器取当前时刻，落在当前自然月（UTC）")
    void defaultConstructorUsesNow() {
        LegacySalesReport report = new LegacySalesReport();
        Calendar now = Calendar.getInstance(TimeZone.getTimeZone("UTC"));

        assertEquals(0, report.size());
        assertTrue(report.generatedInMonth(now.get(Calendar.YEAR), now.get(Calendar.MONTH) + 1));
    }
}
