package com.example.legacy;

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;

/**
 * 遗留的销售报表生成器 —— RemasterAgent 的迁移目标文件。
 *
 * <p>这个类刻意把 JDK 8 时代最常见的几类写法集中到一处，让「现代化」这件事有具体的靶子：
 * <ul>
 *   <li>显式装箱 {@code Double.valueOf} 与显式拆箱 {@code doubleValue()}（JDK 9 起视为冗余）</li>
 *   <li>{@link Comparator} 匿名内部类 → lambda / 方法引用</li>
 *   <li>{@link Date} + {@link Calendar} + {@link SimpleDateFormat} → {@code java.time}</li>
 *   <li>手工 {@code StringBuilder} 拼接多行文本 → text block</li>
 * </ul>
 *
 * <p>这些写法在 JDK 21 上<b>全都能编译</b>。这一点很重要：它意味着「遗留」不等于「编译不过」，
 * 而是「编译得过但写法和目标平台脱节」。所以本工程的验收依据不是「能不能编过」，
 * 而是「改写之后行为是否一字不差」—— 这正是 {@code src/test} 下那组测试的作用。
 *
 * <p>公开方法签名与输出文本是本类的<b>可观测契约</b>，迁移后必须逐字保持不变。
 */
public class LegacySalesReport {

    /** 报表时间统一按 UTC 呈现，不带时区会让同一份数据在不同机器上产出不同结果。 */
    private static final TimeZone REPORT_ZONE = TimeZone.getTimeZone("UTC");

    private static final String TIMESTAMP_PATTERN = "yyyy-MM-dd HH:mm:ss";
    private static final String DATE_PATTERN = "yyyy-MM-dd";

    private final List<Double> amounts = new ArrayList<Double>();
    private final Date generatedAt;

    /** 无参构造：以当前时刻生成。 */
    public LegacySalesReport() {
        this(System.currentTimeMillis());
    }

    /**
     * 指定生成时刻。
     *
     * <p>刻意收 {@code long} 而不是 {@link Date}：跨类型的 API 边界交给调用方决定，
     * 本类内部怎么表示时间是自己的实现细节 —— 这一点让后续换成 {@code java.time} 不会外溢。
     */
    public LegacySalesReport(long generatedAtEpochMillis) {
        this.generatedAt = new Date(generatedAtEpochMillis);
    }

    /** 追加一笔金额，允许为 0 或负数（退货场景）。 */
    public void addAmount(double amount) {
        amounts.add(Double.valueOf(amount));
    }

    public int size() {
        return amounts.size();
    }

    public double total() {
        double sum = 0d;
        for (int i = 0; i < amounts.size(); i++) {
            sum += amounts.get(i).doubleValue();
        }
        return sum;
    }

    /** 均值；空报表返回 0 而不是抛异常 —— 空报表是正常业务状态。 */
    public double average() {
        if (amounts.isEmpty()) {
            return 0d;
        }
        return total() / amounts.size();
    }

    /** 金额从高到低排序，返回<b>快照</b>而不是内部列表。 */
    public List<Double> ranked() {
        List<Double> copy = new ArrayList<Double>(amounts);
        Collections.sort(copy, new Comparator<Double>() {
            @Override
            public int compare(Double left, Double right) {
                return Double.compare(right, left);
            }
        });
        return copy;
    }

    /** 生成日期（UTC），形如 {@code 2023-11-14}。 */
    public String generatedDateUtc() {
        return newFormatter(DATE_PATTERN).format(generatedAt);
    }

    /**
     * 生成时刻是否落在给定的自然月内。
     *
     * @param month 从 1 开始，不是 {@link Calendar#MONTH} 那种从 0 开始的偏移量
     */
    public boolean generatedInMonth(int year, int month) {
        Calendar calendar = Calendar.getInstance(REPORT_ZONE);
        calendar.setTime(generatedAt);
        return calendar.get(Calendar.YEAR) == year
                && calendar.get(Calendar.MONTH) + 1 == month;
    }

    /** 报表头部。 */
    public String header() {
        return "Sales report generated at " + newFormatter(TIMESTAMP_PATTERN).format(generatedAt) + " (UTC)";
    }

    /** 报表固定脚注 —— 多行文本，是 text block 的典型适用场景。 */
    public String footer() {
        return "----\n"
                + "legacy-demo sales report\n"
                + "generated by RemasterAgent migration sample\n";
    }

    /** 榜单前 n 行，每行形如 {@code 1: $30.00}；n 超过实际条数时按实际条数输出。 */
    public String topLines(int n) {
        List<Double> sorted = ranked();
        int limit = Math.min(n, sorted.size());
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < limit; i++) {
            if (i > 0) {
                builder.append('\n');
            }
            builder.append(i + 1).append(": ").append(currency(sorted.get(i)));
        }
        return builder.toString();
    }

    /** 完整报表 = 头部 + 榜单 + 脚注。 */
    public String render(int topN) {
        String body = topLines(topN);
        if (body.isEmpty()) {
            return header() + "\n" + footer();
        }
        return header() + "\n" + body + "\n" + footer();
    }

    private static String currency(double amount) {
        return NumberFormat.getCurrencyInstance(Locale.US).format(amount);
    }

    /** 每次新建实例：{@link SimpleDateFormat} 不是线程安全的，共享它是个常见但致命的错误。 */
    private static SimpleDateFormat newFormatter(String pattern) {
        SimpleDateFormat format = new SimpleDateFormat(pattern, Locale.ROOT);
        format.setTimeZone(REPORT_ZONE);
        return format;
    }
}
